name       : python-netifaces
version    : 0.10.4
release    : 3
source     :
    - https://pypi.python.org/packages/source/n/netifaces/netifaces-0.10.4.tar.gz : 9656a169cb83da34d732b0eb72b39373d48774aee009a3d1272b7ea2ce109cde
license    : MIT
summary    : Python - Portable network interface information.
description: |
    An easy way to get the address(es) of the machine’s network interfaces from Python.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
    - python-setuptools
build      : |
    for py in "python" "python3" ; do
        ${py} setup.py build
    done
install    : |
    for py in "python" "python3" ; do
        ${py} setup.py install --root=%installroot% --no-compile -O0
    done
