name       : python-netifaces
version    : 0.10.6
release    : 7
source     :
    - https://files.pythonhosted.org/packages/source/n/netifaces/netifaces-0.10.6.tar.gz : 0c4da523f36d36f1ef92ee183f2512f3ceb9a9d2a45f7d19cda5a42c6689ebe0
license    : MIT
component  : programming.python
summary    : Python - Portable network interface information.
description: |
    An easy way to get the address(es) of the machine’s network interfaces from Python.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
