name: Build

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Pytho
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.1
    - name: Install Microsoft C++ Build Tools
      run: |
        choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Build binary
      run: python setup.py bdist_wheel
